# This is a basic workflow to help you get started with Actions


name: Upload and Download Artifact Example

on:
  workflow_dispatch:

jobs:
  create-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a text file
        run: echo "This is a sample text file." > output.txt

      - name: Upload output.txt as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: output.txt

  download-and-use:
    runs-on: ubuntu-latest
    needs: create-and-upload

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ./downloaded

      - name: Display content of output.txt
        run: cat ./downloaded/output.txt
